### ISSUE TITLE
Joint flips

### ISSUE THREAD

**Issue by mottosso** [janberger/aniMeta#2]
Hi @janberger!

Enjoying this tool so far, but am having this problem which becomes visible once I skin my character; notice the 180 degree flipping around the shoulder area (ignore the bad weights hehe).

This is using the new Bind Skin menu item. Any idea what might be going on?

https://user-images.githubusercontent.com/2152766/150082529-8df78ca3-fe17-4e6e-9fa5-ab250398108f.mp4

**Comment by janberger** [comment]
Chances are that the up vector for the shoulder may not be positioned well. Turn on the show up vector option in the character editor`s general options panel. The Up Vector can be positioned manually during animation and there is a guide to specify it`s default location.
![Unbenannt](https://user-images.githubusercontent.com/41077468/150102344-4ac3e03b-c466-4135-a9c6-510a791234a1.PNG)

**Comment by janberger** [comment]
I have adressed two minor issues with the up vectors. Please pull the latest version and position the guides for the up vectors. A good starting point is a little bit above the upper arm control and little bit off away from the centre of the character. Depending on the pose and animation the up vector`s location may need to be adjusted, kind of like pole vectors for IKs.

**Comment by janberger** [comment]
There are now buttons for the up vectors in the picker.

![Unbenannt2](https://user-images.githubusercontent.com/41077468/150110137-fb721b4a-440f-4e92-97fa-23fb18d87255.PNG)

**Comment by janberger** [comment]
@mottosso  Can we close this issue?

**Comment by mottosso** [comment]
I was hoping to, but I'm still getting this. 😢 

**Full Walkthrough**

https://user-images.githubusercontent.com/2152766/151405253-e6f5cb48-84f8-4d74-98cd-6b575199b4b9.mp4

**Up Vector**

https://user-images.githubusercontent.com/2152766/151405298-e2b127c3-eda1-45bd-b6ae-c3853e82740f.mp4

Any other ideas?

**Comment by janberger** [comment]
![shoulder_flip](https://user-images.githubusercontent.com/41077468/151702226-6d512a9a-19fc-4b3f-b952-78fea86cd4e4.gif)
I see, it is an issue in the IK mode. I made a fix (version 134 ) and it should be gone now. To pick it up for your rig a full rebuild is required or you can patch your rig. If you want  a full rebuild, I suggest these steps:
1. Save you rig to the rig library ( tab in Character Editor )
2. Save the skinning for all your geos ( you can select multiple geos at once and use aniMetas export skinning feature
3. remove everything you want to keep from the rig hierarchy, ie your geos
4. delete the rig
5. Load the rig from the rig library 
6. Move your geos into the rig`s geo group
7. load the skinning for your geos

That`s it, usually a switch from rig to guide mode and back is all that is necessary to pick up rig changes, unfortunately not in this case. 

If you want to patch your rig (corresponds to right side of the rig):
1. Create a nul for the object 'Shoulder_Blend_Lft_Loc' wit haniMetas create nul feature
2. Create a ParentConstraint from 'Clavicle_Lft_Jnt' to this nul with maintainOffset off

Please let me know if this resolves your issue.

**Comment by janberger** [comment]
Did you ever get a chance to review the changes and see if your issue has been fixed?

**Comment by alanjfs** [comment]
I did not, sorry. Also holiday at the moment, so will be unable to try it again for at least another week.

**Comment by mottosso** [comment]
I did not, sorry. Also holiday at the moment, so will be unable to try it again for at least another week.

**Comment by janberger** [comment]
I assume this to be resolved, if not, please let me know.
