### ISSUE TITLE
Quadruped Character Support

### ISSUE THREAD

**Issue by mottosso** [janberger/aniMeta#5]
Heya! Looking into using this for one of my characters, but was faced by an inability to rotate the guides. 😓 

https://user-images.githubusercontent.com/2152766/162636664-b0dd27cf-0324-4421-847c-6d82f14ffd79.mp4

So, my question to you; any plans on making this work on quadruped characters? 😺

**Comment by janberger** [comment]
The attributes are just locked, it is meant to prevent users from accidental edits, you can just unlock the attributes with the channel control.

**Comment by janberger** [comment]
In the latest version Translate and rotate attributes are no longer locked on guides.

**Comment by janberger** [comment]
Issue resolved
