### ISSUE TITLE
Reset shoulder joint issue

### ISSUE THREAD

**Issue by Klockbox** [janberger/aniMeta#6]
Hi!
Using animeta for a personal project at the moment.
The behavior of the shoulder joint changes after using the Reset All or the Reset Selected Button on the shoulder joint.

Grüße,

Tim

https://github.com/janberger/aniMeta/assets/150134147/c747084d-c1ef-4bcb-a73a-8b3a862b564c

**Comment by janberger** [comment]
Hi,
thanks for point ing this out. The issue has been adressed and an updated version can be pulled that resets controls properly, Note, also the rotate order attribute was affected when set to a non-default value.
